config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'registrations'
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in', as: :users_guest_sign_in
  end
  get "up" => "rails/health#show", as: :rails_health_check
  get '/', to: 'home#index'

  resources :users do
    resources :will_videos, only: [:new, :create, :show, :edit, :destroy]
    resources :memorial_photos, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :funeral_preferences, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :funeral_hall_map_search, only: [:index]
    resource :birthday, only: [:new, :create, :edit, :update, :destroy]
    resources :insurance_policies, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :insurance_graphs, only: [:index] do
      collection do
        post 'calculate_insurance_amount_by_age'
      end
    end
  end
  resources :contacts, only: [:index, :new, :create] do
    collection do
      post 'confirm'
      post 'done'
    end
  end
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :email, :content
  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 30 }, format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true, length: { maximum: 500 }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    if user_signed_in?
      @contact.email = current_user.email
      @contact.name = current_user.username
    end
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :confirm
    else
      flash.now[:alert] = '必須項目を入力してください。'
      render :index, status: :unprocessable_entity
    end
  end

  def done
    @contact = Contact.new(contact_params)
    if params[:back]
      render :index
    else
      ContactMailer.send_mail(@contact).deliver_now
      render :done
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2><i class="far fa-envelope"></i> お問い合わせ内容確認</h2>
        </div>
        <div class="card-body">
          <%= form_with model: @contact, local: true, data: { turbo: false }, url: done_contacts_path do |f| %>
            <div class="form-group">
              <%= f.hidden_field :name %>
              <p><strong>名前:</strong> <%= @contact.name %></p>
            </div>
            <hr>
            <div class="form-group">
              <%= f.hidden_field :email %>
              <p><strong>メールアドレス:</strong> <%= @contact.email %></p>
            </div>
            <hr>
            <div class="form-group">
              <%= f.hidden_field :content %>
              <p><strong>お問い合わせ内容:</strong><br><%= simple_format(@contact.content) %></p>
            </div>
            <hr>
            <p class="confirmation-message">※この内容で送信します。よろしいですか？</p>
            <div class="d-flex flex-column">
              <%= button_tag(type: "submit", class: "btn btn-primary w-100 mb-2") do %>
                <i class="fas fa-paper-plane"></i><span> 送信</span>
              <% end %>
              <%= button_tag(type: "submit", name: "back", class: "btn btn-secondary w-100 mt-2") do %>
                <i class="fas fa-arrow-left"></i><span> 前の画面に戻る</span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2><i class="far fa-envelope"></i> 送信完了</h2>
        </div>
        <div class="card-body">
          <p class="thank-you-message">ありがとうございます。<br>お問い合わせ内容を送信しました<i class="far fa-laugh-beam fa-beat"></i></p>
          <%= link_to  "/", class: "btn btn-secondary w-100 mt-3", role: "button" do %>
            <i class="fas fa-home"></i><span> トップページへ</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation" role="alert">
    <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div id="error_explanation" class="d-none"></div>
<% end %>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2><i class="far fa-envelope"></i> お問い合わせ</h2>
        </div>
        <div class="card-body">
          <%= form_with model: @contact, local: true, data: { turbo: false }, url: confirm_contacts_path do |f| %>
            <div class="form-group text-start">
              <%= f.label :name, "名前", class: "ml-2 label-bold" %>
              <div class="ml-1 mb-1">
                <span class="badge badge-info rounded-0">必須</span>
              </div>
              <%= f.text_field :name, id: "name", class: "form-control bg-light", placeholder: "名前", value: @contact.name %>
            </div>
            <div class="form-group text-start">
              <%= f.label :email, "メールアドレス", class: "ml-2 label-bold" %>
              <div class="ml-1 mb-1">
                <span class="badge badge-info rounded-0">必須</span>
                <small class="text-muted">例:user@example.com</small>
              </div>
              <%= f.text_field :email, id: "email", class: "form-control bg-light", placeholder: "メールアドレス", value: @contact.email %>
            </div>
            <div class="form-group text-start">
              <%= f.label :content, "お問い合わせ内容", class: "ml-2 label-bold" %>
              <div class="ml-1 mb-1">
                <span class="badge badge-info rounded-0">必須</span>
                <small class="text-muted">パスワードなどの機密情報を含めないでください。</small>
              </div>
              <%= f.text_area :content, id: "content", class: "form-control bg-light", placeholder: "お問い合わせ内容", rows: "5" %>
            </div>
            <div>
              <%= button_tag(type: "submit", class: "btn btn-primary w-100 mt-3") do %>
                <i class="fas fa-eye"></i><span> 確認</span>
              <% end %>
            </div>
          <% end %>
          <%= link_to  "/", class: "btn btn-secondary w-100 mt-3", role: "button" do %>
            <i class="fas fa-home"></i><span> トップページへ</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>