config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'registrations'
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in', as: :users_guest_sign_in
  end
  get "up" => "rails/health#show", as: :rails_health_check
  get '/', to: 'home#index'

  resources :users do
    resources :will_videos, only: [:new, :create, :show, :edit, :destroy]
    resources :memorial_photos, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :funeral_preferences, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :funeral_hall_map_search, only: [:index]
    resource :birthday, only: [:new, :create, :edit, :update, :destroy]
    resources :insurance_policies, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :insurance_graphs, only: [:index] do
      collection do
        post 'calculate_insurance_amount_by_age'
      end
    end
  end
  resources :contacts, only: [:index, :new, :create] do
    collection do
      post 'confirm'
      post 'done'
    end
  end
end

app/controllers/insurance_graphs_controller.rb
class InsuranceGraphsController < ApplicationController
  include InsuranceHelper
  before_action :set_user

  def index
    @user_age = @user.birthday&.age
    @insurance_policies = @user.insurance_policies
    @insurance_amounts = calculate_insurance_amounts_for_graph(@insurance_policies, @user_age)

    if session[:age].present?
      @age = session.delete(:age)
      @total_amount = session.delete(:total_amount)
    end
  end

  def calculate_insurance_amount_by_age
    @user_age = @user.birthday&.age

    if params[:age].present?
      @age = params[:age].to_i

      if @age < @user_age
        redirect_to user_insurance_graphs_path(@user), alert: "年齢は#{@user_age}歳以上にしてください。"
        return
      elsif @age > 100
        redirect_to user_insurance_graphs_path(@user), alert: '年齢は100歳以下で入力してください。'
        return
      end

      @insurance_policies = @user.insurance_policies
      @total_amount = calculate_total_amount(@insurance_policies, @age)
      session[:age] = @age
      session[:total_amount] = @total_amount
      redirect_to user_insurance_graphs_path(@user)
    else
      redirect_to user_insurance_graphs_path(@user), alert: '年齢を入力してください。'
    end
  end

  private

  def set_user
    @user = User.find_by(id: params[:user_id])
  end
end

app/views/insurance_graphs/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-20">
      <div class="card">
        <div class="card-header">
          <h1 class="mb-0">
            <% if current_user.avatar.attached? %>
              <%= image_tag rails_blob_path(current_user.avatar), class: "avatar-image" %>
            <% else %>
              <%= image_tag("https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png", class: "avatar-image") %>
            <% end %>
            <%= current_user.username %>様
            <% if @insurance_policies.empty? %>
              <%= link_to "(#{current_user.birthday.age})", edit_user_birthday_path(current_user), class: "text-decoration-none" %>の保険金額
            <% else %>
              (<%= current_user.birthday.age %>)の保険金額
            <% end %>
            <i class="far fa-id-card"></i>
          </h1>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <% if @insurance_policies.empty? %>
              <%= link_to edit_user_birthday_path(current_user), class: "text-decoration-none" do %>
                <i class="fas fa-birthday-cake"></i>
                <%= current_user.birthday.date_of_birth %>
              <% end %>
            <% else %>
              <i class="fas fa-birthday-cake"></i>
              <%= current_user.birthday.date_of_birth %>
              <div class="mt-1">
                <small class="text-muted">※生年月日を編集するには保険契約を０にする必要があります。</small>
              </div>
            <% end %>
          </div>
          <div class="mb-4">
            <%= form_with url: calculate_insurance_amount_by_age_user_insurance_graphs_path(@user), method: :post, local: true, class: "form-inline justify-content-center" do %>
              <div class="form-group mb-2">
                <%= label_tag :age, "指定年齢で保険金額計算ができます", class: "mr-2" %>
                <div class="d-inline-flex align-items-center">
                  <%= number_field_tag :age, nil, class: "form-control bg-light mr-2 custom-width", autocomplete: "off" %>歳
                </div>
              </div>
              <%= button_tag(type: "submit", class: "btn btn-primary w-100 mt-3", data: { turbo: false }) do %>
                <i class="fas fa-calculator"></i><span> 計算</span>
              <% end %>
            <% end %>
          </div>
          <% if @age.present? %>
            <% if @total_amount > 0 %>
              <h2 class="alert alert-success"><%= current_user.username %>様が<%= @age %>歳時点でお亡くなりになると<%= @total_amount / 10000 %>万円家族に遺せます</h2>
            <% else %>
              <h2 class="alert alert-danger"><i class="fas fa-exclamation-triangle"></i><%= current_user.username %>様が<%= @age %>歳時点でお亡くなりになられても遺せるお金はありません</h2>
            <% end %>
          <% end %>
        </div>
        <div class="chart-container" data-age="<%= current_user.birthday.age %>" data-insurance-amounts="<%= @insurance_amounts.to_json %>">
          <canvas id="myBarChart"></canvas>
        </div>
        <div class="card-header">
          <h2><i class="fas fa-file-alt"></i> 保険契約一覧</h2>
        </div>
        <div class="card-body">
          <% if @insurance_policies.empty? %>
            <p>保険の登録がありません。</p>
          <% else %>
            <div class="table-responsive d-none d-md-block">
              <table class="table">
                <thead>
                  <tr>
                    <th>保険会社</th>
                    <th>保険種類</th>
                    <th>保険金額</th>
                    <th>保険期間</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @insurance_policies.each do |policy| %>
                    <tr>
                      <td><%= policy.insurance_company %></td>
                      <td><%= policy.insurance_type %></td>
                      <td><%= number_with_delimiter(policy.insurance_amount / 10000) %>万円</td>
                      <td><%= policy.insurance_period == 100 ? "終身" : "#{policy.insurance_period}歳" %></td>
                      <td>
                        <div class="dropdown">
                          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-bars"></i>
                          </button>
                          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><%= link_to "詳細", user_insurance_policy_path(@user, policy), class: "dropdown-item" %></li>
                            <li><%= link_to "編集", edit_user_insurance_policy_path(@user, policy), class: "dropdown-item" %></li>
                          </ul>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div class="d-block d-md-none">
              <% @insurance_policies.each do |policy| %>
                <div class="card mb-3">
                  <div class="card-body">
                    <h5 class="card-title"><%= policy.insurance_company %></h5>
                    <p class="card-text">
                      <strong>保険種類:</strong> <%= policy.insurance_type %><br>
                      <strong>保険金額:</strong> <%= number_with_delimiter(policy.insurance_amount / 10000) %>万円<br>
                      <strong>保険期間:</strong> <%= policy.insurance_period == 100 ? "終身" : "#{policy.insurance_period}歳" %>
                    </p>
                    <div>
                      <%= link_to "詳細", user_insurance_policy_path(@user, policy), class: "btn btn-primary btn-sm me-2" %>
                      <%= link_to "編集", edit_user_insurance_policy_path(@user, policy), class: "btn btn-secondary btn-sm me-2 mt-2 w-100" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= link_to new_user_insurance_policy_path(@user), class: "btn btn-success w-100 mt-2" do %>
            <i class="fas fa-plus"></i><span> 新しい保険契約を追加</span>
          <% end %>
          <%= link_to "/", class: "btn btn-secondary w-100 mt-3", role: "button" do %>
            <i class="fas fa-home"></i><span> トップページへ</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>