config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  registrations: 'registrations'
}
  devise_scope :user do
    post 'users/guest_sign_in', to: 'sessions#guest_sign_in', as: :users_guest_sign_in
  end
  get "up" => "rails/health#show", as: :rails_health_check
  get '/', to: 'home#index'

  resources :users do
    resources :will_videos, only: [:new, :create, :show, :edit, :destroy]
    resources :memorial_photos, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :funeral_preferences, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :funeral_hall_map_search, only: [:index]
    resource :birthday, only: [:new, :create, :edit, :update, :destroy]
    resources :insurance_policies, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :insurance_graphs, only: [:index] do
      collection do
        post 'calculate_insurance_amount_by_age'
      end
    end
  end
  resources :contacts, only: [:index, :new, :create] do
    collection do
      post 'confirm'
      post 'done'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>エンディングノート</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.ico.png" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:js) %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <%= link_to "エンディングノート", "/", class: "navbar-brand navbar-brand-tablet hover-action-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item hover-action-brand">
              <%= link_to (user_signed_in? ? (current_user.birthday ? user_insurance_graphs_path(current_user) : new_user_birthday_path(current_user)) : new_user_session_path), class: "nav-link", data: { turbo: false } do %>
                <i class="far fa-id-card"></i><span> ご加入中の保険</span>
              <% end %>
            </li>
            <li class="nav-item hover-action-brand">
              <%= link_to (user_signed_in? ? user_funeral_hall_map_search_index_path(current_user) : new_user_session_path), data: { turbo: "false" }, class: "nav-link" do %>
                <i class="fas fa-street-view"></i><span> 葬儀場MAP</span>
              <% end %>
            </li>
            <li class="nav-item hover-action-brand">
              <%= link_to (user_signed_in? ? (current_user.funeral_preference.present? ? user_funeral_preference_path(current_user, current_user.funeral_preference) : new_user_funeral_preference_path(current_user)) : new_user_session_path), data: { turbo: "false" }, class: "nav-link" do %>
                <i class="fas fa-users"></i><span> ご葬儀プラン</span>
              <% end %>
            </li>
            <li class="nav-item hover-action-brand">
              <%= link_to (user_signed_in? ? (current_user.will_videos.any? ? user_will_video_path(current_user, current_user.will_videos.last) : new_user_will_video_path(current_user)) : new_user_session_path), data: { turbo: "false" }, class: "nav-link" do %>
                <i class="fas fa-video"></i><span> ご遺言動画</span>
              <% end %>
            </li>
            <li class="nav-item hover-action-brand">
              <%= link_to (user_signed_in? ? (current_user.memorial_photos.any? ? user_memorial_photos_path(current_user) : new_user_memorial_photo_path(current_user)) : new_user_session_path), data: { turbo: "false" }, class: "nav-link" do %>
                <i class="fas fa-camera"></i><span> ご遺影写真</span>
              <% end %>
            </li>
            <li class="nav-item hover-action-brand">
              <%= link_to contacts_path, class: "nav-link" do %>
                <i class="fas fa-envelope"></i><span> お問い合わせ</span>
              <% end %>
            </li>
          </ul>
          <% if current_user %>
            <%= link_to edit_user_registration_path, data: { turbo: "false" }, role: "button", class: "text-decoration-none" do %>
              <% if current_user.avatar.attached? %>
                <%= image_tag rails_blob_path(current_user.avatar), class: "avatar-image" %>
              <% else %>
                <%= image_tag "https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png", class: "avatar-image" %>
              <% end %>
              <span class="user_name text-decoration-none"><%= current_user.username %> 様</span>
            <% end %>
            <% if user_signed_in? %>
              <%= form_tag destroy_user_session_path, method: :delete, data: { turbo_confirm: "ログアウトしますか？" } do %>
                <%= button_tag type: "submit", class: "btn btn-outline-success my-2 my-sm-0 me-2", role: "button" do %>
                  <i class="fas fa-sign-out-alt"></i><span class="tablet-hide"> ログアウト</span>
                <% end %>
              <% end %>
            <% end %>
          <% else %>
            <%= link_to new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0 me-2", data: { turbo: "false" }, role: "button" do %>
              <i class="fas fa-user-plus"></i><span> 新規登録</span>
            <% end %>
            <%= link_to new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0 me-2", data: { turbo: "false" }, role: "button" do %>
              <i class="fas fa-sign-in-alt"></i><span> ログイン</span>
            <% end %>
            <%= form_with url: users_guest_sign_in_path, method: :post, local: true do |form| %>
              <%= button_tag type: "submit", class: "btn btn-outline-success my-2 my-sm-0" do %>
                <i class="fas fa-user-secret"></i><span> ゲスト</span>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <div>
      <%= yield %>
    </div>
    <footer class="bg-dark text-white mt-4">
      <div class="container-fluid py-3">
        <div class="row">
        <div class="text-center py-3" "col-md-6">
            <%= link_to "エンディングノート 〜家族のために〜", "/", class: "navbar-brand hover-action-brand" %>
          </div>
        </div>
      </div>
      <div class="text-center py-3 bg-dark text-white">
        <p>© 2024 Ending.note. All rights reserved.</p>
        <p>Created by Takuro Miyanaga</p>
        <div class="small-text">
          <p>当サイトでは金融庁登録の保険会社名を使用しています。</p>
          <p>当サイトでは厚生労働省及び農林水産省登録の共済団体名を使用しています。</p>
        </div>
      </div>
    </footer>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>